dist: trusty
sudo: required
services:
- docker
language: go
go:
  - "1.11.x"

before_install:
# Temporary because we are running this in our own repo but needs to ultimately run
# under skytap
- bash scripts/temp-repo-adjust.sh

install:
# This script is used by the Travis build to install a cookie for
# go.googlesource.com so rate limits are higher when using `go get` to fetch
# packages that live there.
# See: https://github.com/golang/go/issues/12933
- bash scripts/gogetcookie.sh

script:
- make test
- make vet
#- make website-test

branches:
  only:
  - master
matrix:
  fast_finish: true
  allow_failures:
  - go: tip
env:
  - GOFLAGS=-mod=vendor GO111MODULE=on
